Pos_pid:
  Kp_x: 1.0
  Kp_y: 1.0
  Kp_z: 2.0
  Kd_x: 0.5
  Kd_y: 0.5
  Kd_z: 0.5
  Ki_x: 0.2
  Ki_y: 0.2
  Ki_z: 0.2
  px_error_max: 0.6
  py_error_max: 0.6
  pz_error_max: 1.0

cascade_pid:
  Kp_px: 1.5
  Kp_py: 1.5
  Kp_pz: 3.0
  Kd_px: 0.0
  Kd_py: 0.0
  Kd_pz: 0.0
  Ki_px: 0.0
  Ki_py: 0.0
  Ki_pz: 0.0
  Kp_vx: 3.3
  Kp_vy: 3.3
  Kp_vz: 5.0
  Kd_vx: 0.15
  Kd_vy: 0.15
  Kd_vz: 0.20
  Ki_vx: 0.10
  Ki_vy: 0.10
  Ki_vz: 0.10
  maxVel: 2.0
  maxAcc: 4.0
  pos_error_max: 1.5
  pos_integral_max: 0.8
  vel_error_max: 1.0
  vel_integral_max: 0.8
